### ISSUE TITLE
!yt ne retourne pas de message quand aucun résultat trouvé

### ISSUE THREAD

**Issue by logscl** [logscl/nicobot-slack#61]
- Requested by bennymaczenface

**Comment by logscl** [comment]
[INFO] 2016-03-23 10:24:12,265: [Grizzly(1)] com.st.nicobot.internal.bot.NicoBotImpl - MSG [SLACK_MESSAGE_POSTED] ON CHAN general BY bennymaczenface : !yt j ai vu ta mere sur slackroulette
[ERROR] 2016-03-23 10:24:12,861: [Grizzly(1)] com.st.nicobot.bot.cmd.YoutubeSearch - JSONArray[0] not found.
org.codehaus.jettison.json.JSONException: JSONArray[0] not found.
        at org.codehaus.jettison.json.JSONArray.get(JSONArray.java:162)
        at org.codehaus.jettison.json.JSONArray.getJSONObject(JSONArray.java:254)
        at com.st.nicobot.bot.cmd.YoutubeSearch.doCommand(YoutubeSearch.java:76)
